-- 创建数据库
CREATE DATABASE IF NOT EXISTS aisnap;

-- 使用数据库
USE aisnap;

-- 创建用户表
CREATE TABLE IF NOT EXISTS User (
  id VARCHAR(36) PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  name VARCHAR(255),
  avatar VARCHAR(512),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 创建转换记录表
CREATE TABLE IF NOT EXISTS Conversion (
  id VARCHAR(36) PRIMARY KEY,
  userId VARCHAR(36),
  inputType VARCHAR(50) NOT NULL,
  outputType VARCHAR(50) NOT NULL,
  inputFile VARCHAR(512),
  outputFile VARCHAR(512),
  template TEXT,
  status VARCHAR(50) DEFAULT 'pending',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE SET NULL
);